import { iranSansX } from "@/constants/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      dir="rtl"
      lang="fa-IR"
      className={cn(
        "h-full",
        "antialiased",
        iranSansX.variable,
        "font-iransanx",
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
